export const ADD_BUDGET = 'ADD_BUDGET';
export const ADD_BUDGET_SUCCESS = 'ADD_BUDGET_SUCCESS';
export const ADD_BUDGET_FAILED = 'ADD_BUDGET_FAILED';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const ADD_EXPENSE_FAILED = 'ADD_EXPENSE_FAILED';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';

export const FETCH_EXPENSE_SUMMARY = 'FETCH_EXPENSE_SUMMARY';
export const FETCH_EXPENSE_SUMMARY_SUCCESS = 'FETCH_EXPENSE_SUMMARY_SUCCESS';
export const FETCH_EXPENSE_SUMMARY_FAILED = 'FETCH_EXPENSE_SUMMARY_FAILED';

export const FETCH_EXPENSE_HISTORY = 'FETCH_EXPENSE_HISTORY';
export const FETCH_EXPENSE_HISTORY_SUCCESS = 'FETCH_EXPENSE_HISTORY_SUCCESS';
export const FETCH_EXPENSE_HISTORY_FAILED = 'FETCH_EXPENSE_HISTORY_FAILED';
